Add SKIP_LB_CREATION param to bbl-up task
[#153272361]

Signed-off-by: Iryna Shustava <ishustava@pivotal.io>

diff --git a/bbl-up/task b/bbl-up/task
--- a/bbl-up/task
+++ b/bbl-up/task
@@ -10,10 +10,23 @@ function check_fast_fails() {
     exit 1
   fi
 
+<<<<<<< HEAD
   if [ -z "${LB_DOMAIN}" ] && [ "${BBL_LB_TYPE}" == "cf" ]; then
     echo "\$LB_DOMAIN is a required parameter when \$BBL_LB_TYPE=cf.  Please set the domain."
     exit 1
   fi
+=======
+  if [ "${create_lbs}" != "true" ]; then
+    if [ "${BBL_IAAS}" != "gcp" ]; then
+      echo "\$IS_BOSH_LITE requires \$BBL_IAAS to be set to 'gcp'"
+      exit 1
+    fi
+  else
+    if [ -z "${LB_DOMAIN}" ]; then
+      echo "\$LB_DOMAIN is a required parameter.  Please set the domain."
+      exit 1
+    fi
+>>>>>>> 258ba95... Add SKIP_LB_CREATION param to bbl-up task
 
   if [ -n "${LB_DOMAIN}" ] && [ "${BBL_LB_TYPE}" == "concourse" ]; then
     echo "\$LB_DOMAIN should not be set when \$BBL_LB_TYPE=concourse."
